FROM golang:1.22

ADD go.mod go.sum /

RUN go mod download

WORKDIR /app

COPY . .

ENV GO_ENV=production
ENV VISA_APPOINTMENT_WATCHER_USERNAME=$VISA_APPOINTMENT_WATCHER_USERNAME
ENV VISA_APPOINTMENT_WATCHER_PASSWORD=$VISA_APPOINTMENT_WATCHER_PASSWORD
ENV VISA_APPOINTMENT_WATCHER_ALERT_PHONE_NUMBER=$VISA_APPOINTMENT_WATCHER_ALERT_PHONE_NUMBER

RUN go build -o /app/visa_appointment_watcher cmd/visa_appointment_watcher/main.go

EXPOSE 3000
CMD ["visa_appointment_watcher"]

