# Name of your application. Used to uniquely configure containers.
service: visa_appointment_watcher
# Name of the container image.
image: troptropcontent/visa_appointment_watcher
builder:
  multiarch: false
volumes:
  - storage:/storage
  - logs:/logs
servers:
  web:
    env:  
      secret:
        - HEADLESS_BROWSER_HOST
        - VISA_APPOINTMENT_WATCHER_USERNAME
        - VISA_APPOINTMENT_WATCHER_PASSWORD
        - VISA_APPOINTMENT_WATCHER_ALERT_PHONE_NUMBER
    hosts:
      - 51.68.196.119
    labels:
      traefik.http.routers.visa_appointment_watcher.entrypoints: websecure
      traefik.http.routers.visa_appointment_watcher.rule: Host(`visa-appointment-watcher.thepocman.com`)
      traefik.http.routers.visa_appointment_watcher.tls: "true"
      traefik.http.routers.visa_appointment_watcher.tls.certresolver: letsencrypt
accessories:
  headless_browser:
    image: ghcr.io/go-rod/rod
    hosts:
      - 51.68.196.119
    port: 7317
registry:
  username: troptropcontent
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: ubuntu
traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    log.level: "DEBUG"
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "tomecrepont@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
