name: CD

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: production

    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      HEADLESS_BROWSER_HOST: ${{ secrets.HEADLESS_BROWSER_HOST }}
      VISA_APPOINTMENT_WATCHER_USERNAME: ${{ secrets.VISA_APPOINTMENT_WATCHER_USERNAME }}
      VISA_APPOINTMENT_WATCHER_PASSWORD: ${{ secrets.VISA_APPOINTMENT_WATCHER_PASSWORD }}
      VISA_APPOINTMENT_WATCHER_ALERT_PHONE_NUMBER: ${{ secrets.VISA_APPOINTMENT_WATCHER_ALERT_PHONE_NUMBER }}
      VAW_TWILIO_NUMBER: ${{ secrets.VAW_TWILIO_NUMBER }}
      VAW_TWILIO_ACCOUNT_SID: ${{ secrets.VAW_TWILIO_ACCOUNT_SID }}
      VAW_TWILIO_AUTH_TOKEN: ${{ secrets.VAW_TWILIO_AUTH_TOKEN }}
      VAW_META_ACCOUNT_ID: ${{ secrets.VAW_META_ACCOUNT_ID }}
      VAW_META_TOKEN: ${{ secrets.VAW_META_TOKEN }}
      VAW_GOOGLE_CLIENT_ID: ${{ secrets.VAW_GOOGLE_CLIENT_ID }}
      VAW_GOOGLE_CLIENT_SECRET: ${{ secrets.VAW_GOOGLE_CLIENT_SECRET }}
      VAW_GOOGLE_ACCESS_TOKEN: ${{ secrets.VAW_GOOGLE_ACCESS_TOKEN }}
      VAW_GOOGLE_REFRESH_TOKEN: ${{ secrets.VAW_GOOGLE_REFRESH_TOKEN }}
      VAW_ADMIN_PHONE_NUMBER: ${{ secrets.VAW_ADMIN_PHONE_NUMBER }}
      VAW_ADMIN_EMAIL: ${{ secrets.VAW_ADMIN_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install specific_install
          gem specific_install https://github.com/basecamp/kamal.git 

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Push ENV variables
        run: kamal env push
      
      - name: Run deploy command
        run: kamal deploy

